#!/bin/bash
#FUNCIONS
function menu(){
	clear
	echo -e "\n DECIDEIX QUE FER:\n
	1 - Sumar
	2 - Restar
	3 - Dividir
	4 - Multiplicar
	0 - Salir\n"
	read num	
}
function check_number(){
	if [[ $num =~ [0-4] ]]; then	
		echo "Be"
		exit
	else
		echo "MAL"
		exit
	fi

}


#VARIABLES
declare -ig num

##########
###MAIN###
##########
menu
while true
do
	check_number
done
